version: "3.9"

services:
  postgres:
    image: postgres:12
    restart: always
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 2s
      retries: 3

  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
  auth-service:
    build:
      context: auth
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
volumes:
  app-db-data:
  root-home: